### ISSUE TITLE
Incorrect behavior when accessing hidden fields of another object (XBase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1335]
**Describe the bug**
When I access inside a method the hidden fields of an object that is not `self`, but of the same class, I get `nil`

**To Reproduce**
```
procedure Main()
    local o := BigNumber():new(3)
    local o2 := BigNumber():new(4)

    ? o:getNumber()
    ? o2:getNumber()
    o:Increment(o2)
    ? o:getNumber()

    wait
return


class BigNumber
exported:
   inline method Init(a)
       ::_a := a
   return

   inline method Increment(o)
       ? ::_a, o:_a
       //::_a += o:_a // program falls, because o:_a is nil
   return self

   inline method getNumber()
   return ::_a

hidden:
   var _a
endclass
```

**Expected behavior (xBase++ exe)**
Output
```
3
4
3          4
3
```

**Actual behavior (X# exe)**
```
3
4
3 NIL
3
```

**Additional context**
X# Compiler version 2.17.0.3 (release)
-dialect:xBase++ -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
The problem in this code is caused by the fact that the parameter `o` for the Increment() method is untyped.
The compiler generates code to perform a late bound member access on the field/property (member)  `_a` and it expects that it can only access public members.
I'll see if I can detect inside the IVarGet() function (that implements the late bound member access) that the the variable `o` belongs to the same type as the method from which the function is called. In that case IVarGet() should also allow access to hidden and protected members. And maybe, when IVarGet() is called from a method in a subclass, it should allow access to protected but not to hidden members.

**Comment by RobertvanderHulst** [comment]
Declaring `o` as BigNumber should fix this.

**Comment by DenGhostYY** [comment]
In my opinion, it is better to improve the function `IVarGet()` to facilitate the process of migration from XBase++ to XSharp

**Comment by cpyrgas** [comment]
Confirmed fixed

**Comment by cpyrgas** [comment]
Indeed, problem still exists when /xpp1 is enabled. It works fine when the compiler option is disabled.

**Comment by cpyrgas** [comment]
All confirmed fixed for 2.20
