### ISSUE TITLE
Exception with default parameters from type float

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1684]
In the following example a untyped call to TestMethodNotWorking fails and an InvalidCastException from double to float is thrown.

```
class TestBase
   public method TestMethodNotWorking(x := 1 as float) as void
      Console.WriteLine(i"TestMethodNotWorking {x}")
      return

   public method TestMethodWorking(x := 1 as int) as void
      Console.WriteLine(i"TestMethodWorking {x}")
      return
end class


function Start() as void strict
   local test := TestBase{} as TestBase
   local test2 as usual
   test2 := test


   test.TestMethodWorking()
   test2.TestMethodWorking()


   test.TestMethodNotWorking()
   test2.TestMethodNotWorking()

   Console.ReadLine()
   return
```

Normally default parameters with the type float should work in the same way as int

[XSharpTests.zip](https://github.com/user-attachments/files/18671303/XSharpTests.zip)

**Comment by hpetriffer** [comment]
Another problem with default parameters is the following case:
`public method TestMethodNotWorking(x := null as float) as void`

In this case I expect a warning or compile time error (same as when assign it to a local variable: error XS0037: Cannot convert null to 'float' because it is a non-nullable value type). At the moment I don't get an compile time error. The value is converted to 0 if I call the method with a typed object. If I call the method untyped I get an Cast exception.

**Comment by cpyrgas** [comment]
Original problem is fixed, but there's still an inconsistency reported in https://github.com/X-Sharp/XSharpPublic/issues/1684#issuecomment-2636585461

This code results to a correct compiler error when assigning NULL to FLOAT in the method body, but no error or waring is reported when doing the same thing on the default parameter assignment.

```
PROCEDURE TestNull(x := NULL AS FLOAT) AS VOID // no error
x := NULL // error XS0037: Cannot convert null to 'float' because it is a non-nullable value type
```

**Comment by RobertvanderHulst** [comment]
Chris,
There is a BIG difference between the two lines:
The `:= NULL` in the parameter declaration generates an attribute. This is handled by the parser and does not get sent to the backend of the compiler
The `:= NULL` in the assignment gets interpreted by the compiler.

**Comment by cpyrgas** [comment]
Robert,
Yes, but this is an implementation detail. To the programmer it's the same thing, so he would expect the same behavior in both cases.

**Comment by cpyrgas** [comment]
Robert, I'm still not seeing no errors or warnings in code like this:

FUNCTION Foo(n := NULL AS INT, f := NULL AS FLOAT) AS VOID

Maybe the build in Actions has not been updated?

**Comment by RobertvanderHulst** [comment]
I have merged the changes into main and started the action to produce the new DLL.

**Comment by cpyrgas** [comment]
Confirmed fixed. It's now an error assigning NULL to a structure (not a warning anymore), but I think that's correct behavior.

**Comment by cpyrgas** [comment]
Unfortunately there are still some issues:

1. NULL_PSZ:
// error XS0037: Cannot convert null to 'psz' because it is a non-nullable value type
FUNCTION TestNull(p := NULL_PSZ AS PSZ) AS VOID

2. NULL_SYMBOL
// error XS0037: Cannot convert null to 'psz' because it is a non-nullable value type
FUNCTION TestNull(s := NULL_SYMBOL AS SYMBOL) AS VOID

and there's a bigger issue, but maybe this will be automatically resolved when the above is fixed. Right now, if you have in an app using RP2 code like

```
FUNCTION Start() AS VOID
	LOCAL o AS RpPrinter
	o:PrintPreview()
```

Then the compiler reports 

error XS0037: Cannot convert null to 'symbol' because it is a non-nullable value type

because the PrintPreview() method has a SYMBOL default parameter. But the big problem is that there is no file/line information in the compiler error, so it is very difficult for the user to find what is causing it.

**Comment by cpyrgas** [comment]
Unfortunately there still exist a couple related issues, with late bound calls of methods with default parameter values. I have adjusted the test C936 for them, see the runtime errors below:

```
CLASS TestBase
	METHOD TestNull(s := NULL_STRING AS USUAL, p := NULL_PSZ AS USUAL, o := NULL_OBJECT AS USUAL) AS USUAL
	RETURN s
	METHOD TestNull_PTR(p := NULL_PTR AS USUAL) AS USUAL // 3 errors XS037
	RETURN AsString(p)

	METHOD TestNullPsz(p := NULL_PSZ AS PSZ) AS USUAL
	RETURN AsString(p)
	METHOD TestNullSymbol(s := NULL_SYMBOL AS SYMBOL) AS USUAL
	RETURN AsString(s)
END CLASS


FUNCTION Start() AS VOID STRICT
	LOCAL typed := TestBase{} AS TestBase
	LOCAL untyped AS USUAL
	untyped := typed

	typed:TestNull("abc") // OK
	untyped:TestNull("abc") // Object of type 'System.IntPtr' cannot be converted to type 'XSharp.__Usual'.
	
	LOCAL p AS USUAL
	p := NULL_PSZ // OK
	p := NULL_PTR // OK
	
	typed:TestNull_PTR() // OK
	typed:TestNull_PTR(NULL_PTR) // OK

	untyped:TestNull_PTR() // Object of type 'System.IntPtr' cannot be converted to type 'XSharp.__Usual'.
	untyped:TestNull_PTR(NULL_PTR) // OK


	typed:TestNullPsz() == "") // OK
	typed:TestNullPsz("abc") == "abc") // OK
	typed:TestNullSymbol() == "") // OK
	typed:TestNullSymbol(#abc) == "ABC") // OK

	untyped:TestNullPsz() // Object of type 'System.IntPtr' cannot be converted to type 'XSharp.__Psz'.
	untyped:TestNullPsz("abc") // OK
	untyped:TestNullSymbol() // OK
	untyped:TestNullSymbol(#abc) // OK
```

**Comment by cpyrgas** [comment]
I am afraid this has caused more serious problems, so it is high priority to fix it, or temporarily completely roll back the changes/fixes for now, and look into it again later.

Taken from test C874, this code now always calls the first overload that only has one parameter, no matter the # of parameters passed to it

```
CLASS TestClass
	METHOD Seek(a AS INT) AS INT
		? "a"
	RETURN a
	METHOD Seek(a AS INT, b AS INT) AS INT
		? "b"
	RETURN a+b
	METHOD Seek(a AS INT, b AS INT, c AS INT) AS INT
		? "c"
	RETURN a+b+c
END CLASS

FUNCTION Start() AS VOID
	LOCAL u := TestClass{} AS USUAL
	? u:Seek(1)
	? u:Seek(1,2)
	? u:Seek(1,2,3)

```
