### ISSUE TITLE
Issue with Float and Linq Operation Sum

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#965]
I discovered an issue with the Float data type. It seems, that Float get's converted to Int, if I use the Linq Sum Operator. 

```
function Start() as void strict

    var valueList := List<ValueClass>{} { ValueClass{} { valueFloat := 11.11, valueReal8 := 22.22 } }
    
    var sumFloat := valueList.Sum({ q => q.valueFloat })
    var sumReal8 := valueList.Sum({ q => q.valueReal8 }) 
    
    Console.WriteLine(sumFloat) // Returns 11 (because float seams to be casted to int)
    Console.WriteLine(sumReal8) // Returns 22.22 which is correct
    
    console.ReadKey()
return
    
class ValueClass
    property valueFloat as float auto
    property valueReal8 as real8 auto
end class
```

This Zip file contains a project with this example

[XSharpTestsFloat.zip](https://github.com/X-Sharp/XSharpPublic/files/8081105/XSharpTestsFloat.zip)

**Comment by cpyrgas** [comment]
I thin it's not possible to return a FLOAT in this case, looking at the available overloads of the Sum() method, it needs to be one of those standard numeric types that are defined in the framework: INT, INT64, REAL4, REAL8, System.Decimal). Even if you try to use a WORD or a BYTE, those also will be converted to INT.

So only solution is to use REAL8 for the FLOAT values, which can be done with

var sumFloat := valueList.Sum({ q => (real8) q.valueFloat })

Not sure if this can/should be done automatically by the compiler, when it sees FLOAT values, will let Robert comment on that.

**Comment by RobertvanderHulst** [comment]
I will have a look, but I am afraid that this will be very difficult to implement.
From what I have seen in the past the compiler follows the following logic to decide which overload to choose and what to do with the parameters:
- it inspects each of the overloads. In this case there are 5 variations with 5 different parameter types: Int32, Int64, Float32, Float64 and Decimal
- it checks the arguments and inspects for the arguments if they can be implicitly converted to one of these argument types.
- We have added logic to the compiler to allow implicit conversion of Floats to Int32 and Int64, to make sure that the assignment of a float to an int does not require an explicit conversion
- As a result each of the overloads of the Sum() method becomes "feasible".
- The Roslyn code then apparently chooses the overload with the Int32 parameter.

In theory we could control this behavior, since we already have code that helps to choose between overloads and we could give precedence to overloads with fractional parameters over overloads with integral parameters.

I will look at this and will try to change that.
However, this is a very "delicate" part of the compiler, since this is used for all decisions when more that one overload of a method is available. So there is a serious chance of side effects.
So I'll try to solve this but cannot promise anything....

**Comment by cpyrgas** [comment]
...and if this can be enabled, the result value will still be a REAL8, not a (VO-style) FLOAT.

**Comment by hpetriffer** [comment]
Aren't the conversions of the class __Float used for the compiler? If I looked there correctly, there is no implicit conversion to INT. All conversions to integers are declared as EXPLICIT.
By the way, it is no problem for us if a Real8 is returned. What is worse is that here you do not have the possibility to use the sum to get a correct result

**Comment by cpyrgas** [comment]
Indeed, the compiler adds an explicit conversion to INT in the generated code, you can see this with ILSpy:

int sumFloat = valueList.Sum((ValueClass q) => (int)q.valueFloat)

Please note that this is done by the c# backend automatically.

**Comment by VolkmarR** [comment]
A possible solution to this problem could be to add the missing Linq function implementations (Sum, Min, Max, Average) for the float data type. 

Here is an example of two possible ways: 

1) I implemented the extension methods for Sum (following the code in the original implementation of linq: https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System.Core/System/Linq/Enumerable.cs) 

2) As an alternative I added an dummy implementation for the Min method and added an Obsolete Error, so that developers get an error, when using this method. 

```
public static class EnumerableFloat

        public static method Sum(self source as IEnumerable<float>) as float
            if (source == null) 
                throw ArgumentNullException{"source"}
            endif
            local sum := 0 as float
            begin checked
                foreach v as float in source
                    sum += v
                next
            end checked
            return sum;

        public static method Sum<TSource>(self source as IEnumerable<TSource>, selector as Func<TSource, float>) as float
            return EnumerableFloat.Sum(Enumerable.Select<TSource, float>(source, selector));

        [Obsolete("The float DataType doesn't work with the Min Method", true)] ;
        public static method Min(self source as IEnumerable<float>) as float
            throw NotImplementedException{}
        
        [Obsolete("The float DataType doesn't work with the Min Method", true)] ;
        public static method Min<TSource>(self source as IEnumerable<TSource>, selector as Func<TSource, float>) as float
            throw NotImplementedException{}

end class
```

**Comment by cpyrgas** [comment]
@VolkmarR , I agree, this is the fastest and least error prone (in regard to breaking something else) solution, to define a suitable extension method as needed. I think we should close the ticket now?

**Comment by VolkmarR** [comment]
Will you add the necessary methods to the XSharp.RT.Dll?

**Comment by cpyrgas** [comment]
@RobertvanderHulst , I think you forgot to commit the change to the XSharp.RT project file, so the new file ExtensionMethods.prg has not become part of it.

**Comment by RobertvanderHulst** [comment]
@cpyrgas That is correct. I have pushed the update now.

**Comment by cpyrgas** [comment]
Robert, the test in the runtime passes now, but in a standalone project, the original sample doesn't. When all vo options are disabled, then there's a compiler error:

`error XS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Sum<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, real4>)' and 'System.Linq.Enumerable.Sum<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, decimal>)'`

If I enable /vo4, then the compiler error goes away, but the code does not work as expected, the Sum() methods of System.Core.dll are used instead, and the result of course is still wrong (returns 11 instead of 11.11)

Possibly I have made some mistake applying the new dll, here's a test sample that you can also test directly:

[ConsoleApplication16.zip](https://github.com/X-Sharp/XSharpPublic/files/8134724/ConsoleApplication16.zip)

**Comment by cpyrgas** [comment]
Confirmed fixed
